binary_sensor:
  # 是否连接到HA
  - platform: status
    id: system_status
    name: "Status"

button:
  # 重启按钮
  - platform: restart
    id: restart_btn
    name: "Restart"

  # 恢复出厂设置按钮
  - id: !extend factory_reset_btn
    internal: false
    name: "Factory Reset"
#    disabled_by_default: true

sensor:
  # 运行时间
  - platform: uptime
    type: timestamp
    name: "Uptime"

  # WiFi信号强度
  - platform: wifi_signal
    id: wifi_signal_db
    name: "WiFi Signal"

  # 芯片温度
  - platform: internal_temperature
    id: chip_temperature
    name: "Internal Temperature"
