packages:
  basic: !include .basic.yaml
  diagnostics: !include .diagnostics.yaml

esphome:
  name: bigbedroom-lights

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

binary_sensor:
  - platform: gpio
    name: "A"
    pin:
      number: GPIO19
      mode:
        input: true
  - platform: gpio
    name: "B"
    pin:
      number: GPIO18
      mode:
        input: true
  - platform: gpio
    name: "C"
    pin:
      number: GPIO17
      mode:
        input: true
  - platform: gpio
    name: "D"
    pin:
      number: GPIO16
      mode:
        input: true
