packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
  basic: !include .basic.yaml
  battery: !include .esp32-s3-box-3.battery.yaml
  fonts: !include .esp32-s3-box-3.fonts.yaml
  radar: !include .esp32-s3-box-3.radar.yaml
  diagnostics: !include .esp32-s3-box-3.diagnostics.yaml

esphome:
  name_add_mac_suffix: false
