packages:
  common: !include .esp32_common.yaml

esphome:
  name: sfa30
  friendly_name: SFA30

esp32:
  board: seeed_xiao_esp32s3
  variant: esp32s3
  framework:
    type: arduino
    version: latest
    platform_version: 6.11.0

i2c:
  sda: GPIO5
  scl: GPIO6

sensor:
  - platform: sfa30
    formaldehyde:
      name: "Formaldehyde"
      device_class: volatile_organic_compounds_parts
    temperature:
      name: "Temperature"
      filters:
        - skip_initial: 2
        - offset: -4.2
    humidity:
      name: "Humidity"
      filters:
        - skip_initial: 2
        - offset: 12.0
    update_interval: 15s
