# https://esphome.io/components/sensor/sgp4x
# https://esphome.io/components/sensor/dht

packages:
  common: !include .esp32_common.yaml

esphome:
  name: sgp4x
  friendly_name: SGP4X

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: latest
    # platform_version: 6.11.0

i2c:
  - sda: 47
    scl: 11
    scan: true

sensor:
  - platform: sgp4x
    voc:
      id: voc
      name: "VOC Index"
    nox:
      name: "NOx Index"
    compensation:
      humidity_source: dht22_humi
      temperature_source: dht22_temp
    update_interval: 31s

  - platform: dht
    pin: 42
    temperature:
      name: "DHT22 Temperature"
      id: dht22_temp
      filters:
        - offset: -1.0
        # - exponential_moving_average:
        #     alpha: 0.1
        #     send_every: 15
        #     send_first_at: 1
    humidity:
      name: "DHT22 Humidity"
      id: dht22_humi
      accuracy_decimals: 1
      filters:
        - offset: 1
    update_interval: 29s
