substitutions:
  PIN_BUTTON: GPIO41
  PIN_RGB_LED: GPIO35
  PIN_PALLET: GPIO8
  PIN_PHOTOTRANSISTOR: GPIO6
  PIN_INFRARED_LED: GPIO7
  PIN_INA_SWITCH: GPIO5
  # PIN_INB_SWITCH: GPIO5

packages:
  common: !include .esp32_common.yaml

esphome:
  name: turtles-feeder
  friendly_name: Turtles Feeder
  on_boot:
    priority: 225
    then:
      - script.execute: check_food
      - if:
          condition:
            lambda: 'return id(pallet).state;'
          then:
            - switch.turn_on: ina_switch

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: arduino
    version: latest
    platform_version: 6.11.0

binary_sensor:
  # 缺料提示
  - platform: template
    id: missing_feed
    name: "Missing Food"
    icon: "mdi:beaker-alert-outline"
    device_class: problem

  # 屏幕按钮
  - platform: gpio
    id: btn
    pin:
      number: $PIN_BUTTON
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:  # 当按钮按下时，执行一次喂食
      then:
        - switch.toggle: ina_switch
    # name: "Button"
    # icon: "mdi:gesture-tap-button"

  # 微动开关，ON表示托盘弹出、代表正在喂食。
  - platform: gpio
    id: pallet
    pin:
      number: $PIN_PALLET
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press: # 当托盘推出时
      then:
        # 记录喂食时间
        - sensor.template.publish:
            id: last_feed_time
            state: !lambda 'return id(ha_time).now().timestamp;'
    on_release: # 当托盘收回时
      then:
        - delay: 1800ms
        # 关闭电机
        - switch.turn_off: ina_switch
        # 然后打开红外发射，检测是否还有库存
        - script.execute: check_food
    # name: "Feeding" # 正在喂食
    # icon: "mdi:coffee-to-go-outline"
    # entity_category: diagnostic
    # disabled_by_default: true

  # 红外接收管，ON表示有障碍、不缺料
  - platform: gpio
    id: phototransistor
    pin: $PIN_PHOTOTRANSISTOR

button:
  # 喂食
  - platform: template
    name: "Feed"
    icon: "mdi:pot-mix"
    on_press:
      then:
        - switch.toggle: ina_switch
  # 检查库存
  - platform: template
    name: "Check Food"
    icon: "mdi:beaker-question-outline"
    on_press:
      then:
        - script.execute: check_food
    entity_category: diagnostic

light:
  - platform: esp32_rmt_led_strip
    pin: $PIN_RGB_LED
    num_leds: 1
    # rmt_channel: 0
    chipset: ws2812
    rgb_order: GRB
    id: rgb_led
    name: "LED"

script:
  - id: check_food  # 检查是否还有食物
    then:
      - switch.turn_on: infrared_led
      - delay: 100ms
      - if:
          condition:
            lambda: 'return id(phototransistor).state;'
          then:
            - binary_sensor.template.publish:
                id: missing_feed
                state: OFF
          else:
            - binary_sensor.template.publish:
                id: missing_feed
                state: ON
      - delay: 50ms
      - switch.turn_off: infrared_led
    mode: single

sensor:
  # 上次喂食时间
  - platform: template
    id: last_feed_time
    name: "Last Feeding Time"
    icon: "mdi:invoice-text-clock-outline"
    accuracy_decimals: 0
    device_class: "TIMESTAMP"

switch:
  # 红外发射管
  - platform: gpio
    id: infrared_led
    pin: $PIN_INFRARED_LED
    # name: "Infrared LED"
    # icon: "mdi:remote"
    # entity_category: diagnostic
    # disabled_by_default: true

  # 电机正转
  - platform: gpio
    id: ina_switch
    pin: $PIN_INA_SWITCH
    # name: "IN-A Switch"
    # icon: "mdi:reload"
    # entity_category: diagnostic
    # disabled_by_default: true

  # # 电机反转
  # - platform: gpio
  #   id: inb_switch
  #   pin: $PIN_INB_SWITCH
  #   # name: "IN-B Switch"
  #   # icon: "mdi:restore"
  #   # entity_category: diagnostic
  #   # disabled_by_default: true
