packages:
  common: !include .esp32_common.yaml

esphome:
  name: watering-unit
  friendly_name: Watering Unit

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: arduino
    version: latest
    platform_version: 6.10.0

binary_sensor:
  # 屏幕按钮
  - platform: gpio
    id: screen_button
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms

display:
  # https://github.com/esphome/feature-requests/issues/2332#issuecomment-1925091376
  - platform: ili9xxx
    model: ST7789V
    dc_pin: GPIO33
    reset_pin: GPIO34
    cs_pin: GPIO15
    dimensions:
      height: 128
      width: 128
      offset_height: 1
      offset_width: 2
    invert_colors: true
    rotation: 270
    update_interval: 1s
    show_test_card: true

i2c:
  # 加速度计
  scl: GPIO39
  sda: GPIO38

sensor:
  # 加速度计
  - platform: mpu6886
    address: 0x68
    # accel_x:
    #   name: "MPU6886 Accel X"
    # accel_y:
    #   name: "MPU6886 Accel Y"
    # accel_z:
    #   name: "MPU6886 Accel z"
    # gyro_x:
    #   name: "MPU6886 Gyro X"
    # gyro_y:
    #   name: "MPU6886 Gyro Y"
    # gyro_z:
    #   name: "MPU6886 Gyro z"
    temperature:
      id: mpu6886_temperature
      name: "MPU6886 Temperature"
      entity_category: diagnostic
    # update_interval: 1s

  - platform: adc
    pin: GPIO1
    attenuation: auto
    name: "Soil Moisture"
    update_interval: 1s

spi:
  # 屏幕
  clk_pin: GPIO17
  mosi_pin: GPIO21

switch:
  # 屏幕背光
  - platform: gpio
    id: backlight
    name: "Backlight"
    icon: "mdi:fit-to-screen"
    pin: GPIO16
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config

  # 水泵
  - platform: gpio
    pin: GPIO2
    id: pump
    name: "Pump"
    restore_mode: ALWAYS_OFF
